server:
  assets-path: /app/assets

theme:
  custom-css-file: /assets/user.css
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65

pages:
  - $include: home.yml
